#!/bin/bash

"$2/JupyterLab.app/Contents/Resources/env_installer/JupyterLabDesktopAppServer-3.1.19-1-MacOSX-x86_64.sh" -b -p "$2/JupyterLab.app/Contents/Resources/jlab_server"

ln -s "$2/JupyterLab.app/Contents/Resources/app/jlab" /usr/local/bin/jlab
chmod 755 "$2/JupyterLab.app/Contents/Resources/app/jlab"

exit 0
