name: Automated Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.12'
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: strict

      - name: Install conda environment for tests
        shell: bash -l {0}
        run: |
          set -eux
          conda env create -f env_installer/jlab_server.yaml
          conda activate jlab_server
          which python
          python --version
          pip list | grep jupyterlab

      - name: Install dependencies
        run: |
          npm install --global yarn --prefer-offline
          yarn install

      - name: Build application
        run: |
          yarn build

      - name: Run tests
        shell: bash -l {0}
        run: |
          set -eux
          conda activate jlab_server
          export JUPYTERLAB_DESKTOP_PYTHON_PATH="$(conda info --base)/envs/jlab_server/bin/python"
          xvfb-run -a yarn test
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results/
            tests/snapshots/
            
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: tests/snapshots/